//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_UP03.EntityDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public int Id { get; set; }
        public Nullable<int> WorkerId { get; set; }
        public Nullable<int> AdminId { get; set; }
        public string TaskText { get; set; }
        public Nullable<int> TaskStatusId { get; set; }
        public Nullable<System.DateTime> TaskDate { get; set; }
    
        public virtual Admin Admin { get; set; }
        public virtual TaskStatus TaskStatus { get; set; }
        public virtual Worker Worker { get; set; }
    }
}
